"""Approved built-in OmN-e Retrospector semantic themes.

Generated from the 2026-09-13 syntax-theme design authority. Keep this module
pure so native CI and migration tests do not require Tk.
"""
from __future__ import annotations

DEFAULT_THEME_NAME = 'Pungent Funk'
PUBLISHED_THEME_ORDER = ['Pungent Funk', 'Space Funk', 'Smitzu Funk', 'LindZ Funk', 'Beth Funk', 'Mik Funk']
THEME_ALIASES = {'Pungent Purple': 'Pungent Funk',
 'Midnight Syntax': 'Space Funk',
 'Lavender Haze': 'Smitzu Funk',
 'CRT Moss': 'LindZ Funk'}
BUILTIN_THEMES = {'Pungent Funk': {'background': '#150D1A',
                  'panel_bg': '#211329',
                  'field_bg': '#170F1E',
                  'foreground': '#F3E9EF',
                  'muted_fg': '#B8A4B3',
                  'button_bg': '#301A36',
                  'button_fg': '#F3E9EF',
                  'active_bg': '#4A2544',
                  'active_fg': '#FFF4D5',
                  'selection_bg': '#6A3256',
                  'selection_fg': '#FFFFFF',
                  'disabled_fg': '#A08A9D',
                  'accent': '#D7B04C',
                  'secondary_accent': '#F05C8A',
                  'tab_bg': '#211329',
                  'tab_selected_bg': '#4A2544',
                  'scrollbar_bg': '#76506B',
                  'scrollbar_trough': '#211329',
                  'scale_bg': '#211329',
                  'scale_trough': '#4A2544',
                  'preview_bg': '#0C0710',
                  'preview_fg': '#F0DDE9',
                  'success_fg': '#7EBB80',
                  'warning_fg': '#D7B04C',
                  'failure_fg': '#F05C8A',
                  'running_fg': '#DA89C8',
                  'sash_color': '#6A465E',
                  'panel_edge': '#503047',
                  'tooltip_bg': '#301A36',
                  'tooltip_fg': '#FFF5FA',
                  'field_fg': '#F3E9EF',
                  'tooltip_delay_ms': 360,
                  'font_family': 'TkDefaultFont',
                  'font_size': 10,
                  'heading_size': 12,
                  'welcome_size': 18,
                  'mono_font': 'TkFixedFont',
                  'mono_size': 9,
                  'tooltip_font_size': 9,
                  'tooltip_wrap_px': 390,
                  'button_pad_x': 8,
                  'button_pad_y': 5,
                  'panel_padding': 8,
                  'border_width': 1,
                  'row_height': 25,
                  'sash_width': 7,
                  'handle_size': 10,
                  'handle_offset': 18,
                  'slider_length': 175,
                  'scrollbar_width': 13},
 'Space Funk': {'background': '#11131B',
                'panel_bg': '#191C28',
                'field_bg': '#0D0F16',
                'foreground': '#DCE1F2',
                'muted_fg': '#9AA3BC',
                'button_bg': '#252A3B',
                'button_fg': '#DCE1F2',
                'active_bg': '#30364B',
                'active_fg': '#F2F4FB',
                'selection_bg': '#465A8C',
                'selection_fg': '#FFFFFF',
                'disabled_fg': '#8C96AE',
                'accent': '#7AA2F7',
                'secondary_accent': '#BB9AF7',
                'tab_bg': '#191C28',
                'tab_selected_bg': '#343B52',
                'scrollbar_bg': '#535D78',
                'scrollbar_trough': '#191C28',
                'scale_bg': '#191C28',
                'scale_trough': '#30364B',
                'preview_bg': '#090A10',
                'preview_fg': '#C9D3F0',
                'success_fg': '#7FB98A',
                'warning_fg': '#D9B968',
                'failure_fg': '#E07191',
                'running_fg': '#8FB2FF',
                'sash_color': '#4B536A',
                'panel_edge': '#383E54',
                'tooltip_bg': '#252A3B',
                'tooltip_fg': '#E8ECF7',
                'field_fg': '#DCE1F2',
                'tooltip_delay_ms': 360,
                'font_family': 'TkDefaultFont',
                'font_size': 10,
                'heading_size': 12,
                'welcome_size': 18,
                'mono_font': 'TkFixedFont',
                'mono_size': 9,
                'tooltip_font_size': 9,
                'tooltip_wrap_px': 390,
                'button_pad_x': 8,
                'button_pad_y': 5,
                'panel_padding': 8,
                'border_width': 1,
                'row_height': 25,
                'sash_width': 7,
                'handle_size': 10,
                'handle_offset': 18,
                'slider_length': 175,
                'scrollbar_width': 13},
 'Smitzu Funk': {'background': '#F1E8DB',
                 'panel_bg': '#FBF5EE',
                 'field_bg': '#FFFDFC',
                 'foreground': '#4A342F',
                 'muted_fg': '#735F5A',
                 'button_bg': '#E7D8EF',
                 'button_fg': '#4A342F',
                 'active_bg': '#D8C4E6',
                 'active_fg': '#33252C',
                 'selection_bg': '#2A78C7',
                 'selection_fg': '#FFFFFF',
                 'disabled_fg': '#806F69',
                 'accent': '#2A78C7',
                 'secondary_accent': '#A54870',
                 'tab_bg': '#E8DDEE',
                 'tab_selected_bg': '#2A78C7',
                 'scrollbar_bg': '#B9A7C7',
                 'scrollbar_trough': '#F1E8DB',
                 'scale_bg': '#FBF5EE',
                 'scale_trough': '#D5C4DF',
                 'preview_bg': '#3B2D38',
                 'preview_fg': '#FFF5F9',
                 'success_fg': '#3B7653',
                 'warning_fg': '#9A6500',
                 'failure_fg': '#A54870',
                 'running_fg': '#246DB5',
                 'sash_color': '#A996B8',
                 'panel_edge': '#CBBAD5',
                 'tooltip_bg': '#4A342F',
                 'tooltip_fg': '#FFF8F1',
                 'field_fg': '#4A342F',
                 'tooltip_delay_ms': 360,
                 'font_family': 'TkDefaultFont',
                 'font_size': 10,
                 'heading_size': 12,
                 'welcome_size': 18,
                 'mono_font': 'TkFixedFont',
                 'mono_size': 9,
                 'tooltip_font_size': 9,
                 'tooltip_wrap_px': 390,
                 'button_pad_x': 8,
                 'button_pad_y': 5,
                 'panel_padding': 8,
                 'border_width': 1,
                 'row_height': 25,
                 'sash_width': 7,
                 'handle_size': 10,
                 'handle_offset': 18,
                 'slider_length': 175,
                 'scrollbar_width': 13},
 'LindZ Funk': {'background': '#0D140F',
                'panel_bg': '#151F18',
                'field_bg': '#0B110D',
                'foreground': '#E6E0C8',
                'muted_fg': '#95A08A',
                'button_bg': '#202C23',
                'button_fg': '#E6E0C8',
                'active_bg': '#2D3B2F',
                'active_fg': '#FFF0C7',
                'selection_bg': '#594434',
                'selection_fg': '#FFFFFF',
                'disabled_fg': '#879284',
                'accent': '#E0B84F',
                'secondary_accent': '#D45F80',
                'tab_bg': '#151F18',
                'tab_selected_bg': '#3A4736',
                'scrollbar_bg': '#53624F',
                'scrollbar_trough': '#151F18',
                'scale_bg': '#151F18',
                'scale_trough': '#2D3B2F',
                'preview_bg': '#070A08',
                'preview_fg': '#DDE6C4',
                'success_fg': '#7FA36A',
                'warning_fg': '#E0B84F',
                'failure_fg': '#D45F80',
                'running_fg': '#D47745',
                'sash_color': '#4E5B49',
                'panel_edge': '#344235',
                'tooltip_bg': '#202C23',
                'tooltip_fg': '#EFEAD5',
                'field_fg': '#E6E0C8',
                'tooltip_delay_ms': 360,
                'font_family': 'TkDefaultFont',
                'font_size': 10,
                'heading_size': 12,
                'welcome_size': 18,
                'mono_font': 'TkFixedFont',
                'mono_size': 9,
                'tooltip_font_size': 9,
                'tooltip_wrap_px': 390,
                'button_pad_x': 8,
                'button_pad_y': 5,
                'panel_padding': 8,
                'border_width': 1,
                'row_height': 25,
                'sash_width': 7,
                'handle_size': 10,
                'handle_offset': 18,
                'slider_length': 175,
                'scrollbar_width': 13},
 'Beth Funk': {'background': '#E8ECE8',
               'panel_bg': '#F7F8F5',
               'field_bg': '#FFFFFF',
               'foreground': '#2E3731',
               'muted_fg': '#5F6A63',
               'button_bg': '#E1E6E2',
               'button_fg': '#2E3731',
               'active_bg': '#D4E2D5',
               'active_fg': '#1F3525',
               'selection_bg': '#2E7544',
               'selection_fg': '#FFFFFF',
               'disabled_fg': '#6F786F',
               'accent': '#2E7544',
               'secondary_accent': '#E0B33C',
               'tab_bg': '#E8ECE8',
               'tab_selected_bg': '#2E7544',
               'scrollbar_bg': '#A9B5AA',
               'scrollbar_trough': '#E8ECE8',
               'scale_bg': '#F7F8F5',
               'scale_trough': '#C5D0C6',
               'preview_bg': '#1D2620',
               'preview_fg': '#EEF6EF',
               'success_fg': '#2E7544',
               'warning_fg': '#8A6300',
               'failure_fg': '#B24C52',
               'running_fg': '#397A5A',
               'sash_color': '#9AA79B',
               'panel_edge': '#C8D0C9',
               'tooltip_bg': '#2E3731',
               'tooltip_fg': '#F7FAF7',
               'field_fg': '#2E3731',
               'tooltip_delay_ms': 360,
               'font_family': 'TkDefaultFont',
               'font_size': 10,
               'heading_size': 12,
               'welcome_size': 18,
               'mono_font': 'TkFixedFont',
               'mono_size': 9,
               'tooltip_font_size': 9,
               'tooltip_wrap_px': 390,
               'button_pad_x': 8,
               'button_pad_y': 5,
               'panel_padding': 8,
               'border_width': 1,
               'row_height': 25,
               'sash_width': 7,
               'handle_size': 10,
               'handle_offset': 18,
               'slider_length': 175,
               'scrollbar_width': 13},
 'Mik Funk': {'background': '#0E1719',
              'panel_bg': '#162326',
              'field_bg': '#0B1315',
              'foreground': '#E9F2F1',
              'muted_fg': '#9AAFAE',
              'button_bg': '#203337',
              'button_fg': '#E9F2F1',
              'active_bg': '#2C494E',
              'active_fg': '#FFF4EB',
              'selection_bg': '#2D6F70',
              'selection_fg': '#FFFFFF',
              'disabled_fg': '#849B9A',
              'accent': '#4CBEB5',
              'secondary_accent': '#D98CAF',
              'tab_bg': '#162326',
              'tab_selected_bg': '#2C494E',
              'scrollbar_bg': '#4F6E70',
              'scrollbar_trough': '#162326',
              'scale_bg': '#162326',
              'scale_trough': '#2C494E',
              'preview_bg': '#071012',
              'preview_fg': '#D5F2EE',
              'success_fg': '#5FC7A2',
              'warning_fg': '#E4A361',
              'failure_fg': '#DB6F7D',
              'running_fg': '#4CBEB5',
              'sash_color': '#466265',
              'panel_edge': '#355256',
              'tooltip_bg': '#203337',
              'tooltip_fg': '#F0F9F8',
              'field_fg': '#E9F2F1',
              'tooltip_delay_ms': 360,
              'font_family': 'TkDefaultFont',
              'font_size': 10,
              'heading_size': 12,
              'welcome_size': 18,
              'mono_font': 'TkFixedFont',
              'mono_size': 9,
              'tooltip_font_size': 9,
              'tooltip_wrap_px': 390,
              'button_pad_x': 8,
              'button_pad_y': 5,
              'panel_padding': 8,
              'border_width': 1,
              'row_height': 25,
              'sash_width': 7,
              'handle_size': 10,
              'handle_offset': 18,
              'slider_length': 175,
              'scrollbar_width': 13}}
BUILTIN_THEME_APPEARANCE = {'Pungent Funk': 'dark',
 'Space Funk': 'dark',
 'Smitzu Funk': 'light',
 'LindZ Funk': 'dark',
 'Beth Funk': 'light',
 'Mik Funk': 'dark'}
BUILTIN_THEME_INTENT = {'Pungent Funk': 'Deep plum substrate with mustard signal colour and vivid red-pink energy.',
 'Space Funk': 'Subtle celestial charcoal/indigo structure with cool blue, violet, restrained pink and muted starlight '
               'yellow.',
 'Smitzu Funk': 'Cutesy warm stationery: beige and milk surfaces, chocolate text, lilac/pink structure and a crisp '
                'blue anchor.',
 'LindZ Funk': 'Dark jungle rather than neon terminal: forest-floor greens and moss with ochre, burnt orange and '
               'berry-red highlights.',
 'Beth Funk': 'Sleek daylight interior: pale grey/white architecture, house-plant greens, charcoal text and warm '
              'golden highlights.',
 'Mik Funk': 'Aquatic petrol/teal substrate with turquoise signal colour and restrained floral/sunset pink, peach and '
             'coral.'}
